name: Run test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v16.13.1
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
